In [1]:
### 시작 및 본인정보 반영
# 반드시 이 cell을 실행하시오
# 실행하지 않을 시 직접 하지 않은 것으로 간주
# 마지막 줄 출력으로 파일명을 설정하고 제출 필수
import platform, psutil, os, datetime
print(platform.processor())
print(str(round(psutil.virtual_memory().total / (1024.0 **3)))+"(GB)")
print(platform.system())
print(platform.version())
print(os.getcwd())
print(datetime.datetime.fromtimestamp(os.path.getctime(os.getcwd())))
print(datetime.datetime.fromtimestamp(os.path.getmtime(os.getcwd())))
print(datetime.datetime.fromtimestamp(os.path.getatime(os.getcwd())))
print(datetime.datetime.now())
title = 'DL_TimeSeries_Forecasting'    # 고정값
name = '김경원'    # 본인 이름을 작성
studentid = '20211011'    # 본인 학번을 작성
# 아래 강좌 명 중 본인이 수강하는 강과명 작성
# 비즈니스데이터사이언스이해, 디지털비즈니스애널리틱스, 비즈니스수요예측, 인공지능기반의사결정, 빅데이터 등
# 비즈니스혁신을위한데이터사이언스응용, 인공지능활용디지털경제플랫폼연구 등
course = '비즈니스수요예측'    
print('다음 출력을 파일명으로 설정하고 제출하시오:', name + '_' + studentid + '_' + course + '_' + title)

Intel64 Family 6 Model 186 Stepping 2, GenuineIntel
32(GB)
Windows
10.0.26200
C:\DataScience\Lecture\[DataScience]
2024-12-12 00:34:16.155373
2025-11-13 15:10:01.507685
2025-11-13 15:10:01.507685
2025-11-13 15:10:16.637009
다음 출력을 파일명으로 설정하고 제출하시오: 김경원_20211011_비즈니스수요예측_DL_TimeSeries_Forecasting

# **Import Library:** 분석에 사용할 모듈 설치

- 강의에서 배운 내용이든 아니든 `자유 설치 및 사용`

In [2]:
import pandas as pd

# **Data Loading:** 분석에 사용할 데이터 불러오기

<center><img src='Image/Advanced/Data_BikeSharingDemand.png' width='800'></center>

| **변수** | **설명** |
|:---:|:---:|
| **datetime** | 날짜시간정보 |
| **season** | 계절 |
| **holiday** | 휴일여부 |
| **workingday** | 주중/주말 |
| **weather** | 날씨 |
| **temp** | 온도 |
| **atemp** | 체감 온도 |
| **humidity** | 습도 |
| **windspeed** | 풍속도 |
| **casual** | 비회원 대여수량 |
| **registered** | 회원 대여수량 |
| **count** | 총 대여수량 |

In [3]:
# 오로지 아래 경로의 데이터만 사용하고 추가적인 데이터 결합은 하지 않음!
location = os.path.join('.', 'Data', 'BikeSharingDemand', 'Bike_Sharing_Demand_Full(TR+VAL).csv')
df = pd.read_csv(location)

# Test Y 데이터 로딩
location = os.path.join('.', 'Data', 'BikeSharingDemand', 'Bike_Sharing_Demand_Full(TEST).csv')
df_test = pd.read_csv(location)
display(df, df_test)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 0:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16
1,2011-01-01 1:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40
2,2011-01-01 2:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32
3,2011-01-01 3:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13
4,2011-01-01 4:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
15206,2012-09-30 19:00,4,0,0,3,20.50,24.240,72,8.9981,34,223,257
15207,2012-09-30 20:00,4,0,0,3,20.50,24.240,72,8.9981,31,163,194
15208,2012-09-30 21:00,4,0,0,1,20.50,24.240,68,0.0000,19,104,123
15209,2012-09-30 22:00,4,0,0,1,19.68,23.485,72,0.0000,15,76,91
15210,2012-09-30 23:00,4,0,0,1,19.68,23.485,72,6.0032,8,49,57

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2012-10-01 0:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45
1,2012-10-01 1:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18
2,2012-10-01 2:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12
3,2012-10-01 3:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
4,2012-10-01 4:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
...,...,...,...,...,...,...,...,...,...,...,...,...
2163,2012-12-31 19:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119
2164,2012-12-31 20:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89
2165,2012-12-31 21:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90
2166,2012-12-31 22:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61
2167,2012-12-31 23:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49

# **Preprocessing:** 데이터 정리 및 패턴 추출하기

- 선택한 `데이터 및 비즈니스 목적` 달성을 위한 `알고리즘 기반 데이터분석`을 하기 위해 필요한 전처리 작업 `자유 진행`하고 `필요성 이유를 주석으로 작성`
- `전처리 순서는 변경가능`하지만 수요예측의 `이론적 처리과정을 제대로 준수하지 않는 경우 채첨포기(0점처리)`
- 각 단계는 `누적되어 결과가 쌓여야` 하며, `독립적인 과정으로 진행할 시 해당 단계는 진행하지 않은 것으로 간주`

- **Total:**
  
> (1) **[시간인덱스 적용 및 원데이터의 빈도설정]**
> 
> (2) **[Down/Up Sampling]** 데이터의 빈도를 일(Day) 기준으로 변환하여 진행
>
> (3) **[Data Split]** 아래 지정된 내용으로 진행
> - Y: `count`
> - X: Y를 제외한 나머지
> - Train: 2011년 1월 ~ 2012년 6월 (18개월)
> - Validate: 2012년 7월 ~ 2012년 9월 (3개월)
> - Test: 2012년 10월 ~ 2012년 12월 (3개월)
>
> `(1+2+3) 위 전처리 과정을 정리 후 함수로 작성 및 실행`

- **Train & Validate:**

> (4) **[Train 시각화]**
> - 모든 독립변수들의 히스토그램(Histogram)
> - 모든 독립변수 별 종속변수의 분포 박스플랏(Boxplot): 필요에 따라 `시각화를 위한 독립변수의 구간화` 사용
> - 모든 독립변수와 종속변수의 상관관계 히드맵(Heatmap)
>   
> (5) **[시간변수 추출]** 연/분기/월/주/일/요일/휴일/근무일/공휴일여부/명절여부 (`미국 워싱턴 기준`)
>
> (6) **[시간특징 추출]** 추세/계절성/이동평균/차분/지연값
>
> (7) **[파생변수 및 나머지 전처리]** `Y 예측에 도움이 될 것으로 예상되는 자유로운 변수생성 및 전처리`
> - 필요여부를 판단하여 주석으로 작성하되, 자유롭고 창의적인 파생변수를 생성 + 알고리즘 학습 전 나머지 필요한 전처리 진행
>
> `(5+6+7) 위 전처리 과정을 정리 후 함수로 작성 및 실행`  

- **Test:**

> (8) **[Test 전처리]** 
> - Text 기간의 독립변수 값들은 미래가 도래해야만 생성되기 때문이 사용할 수가 없음
> - 자유롭고 창의적인 방법으로 Test 기간의 독립변수 값을 생성

## (1) **[시간인덱스 적용 및 원데이터의 빈도설정]**

In [4]:
# 결과확인(아래 변수명으로 사용 및 반드시 결과 출력할 것!)
display(df.head(), df.tail())
display(df.shape)
display(df_test.head(), df_test.tail())
display(df_test.shape)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 0:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16
1,2011-01-01 1:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40
2,2011-01-01 2:00,1,0,0,1,9.02,13.635,80,0.0,5,27,32
3,2011-01-01 3:00,1,0,0,1,9.84,14.395,75,0.0,3,10,13
4,2011-01-01 4:00,1,0,0,1,9.84,14.395,75,0.0,0,1,1

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
15206,2012-09-30 19:00,4,0,0,3,20.50,24.240,72,8.9981,34,223,257
15207,2012-09-30 20:00,4,0,0,3,20.50,24.240,72,8.9981,31,163,194
15208,2012-09-30 21:00,4,0,0,1,20.50,24.240,68,0.0000,19,104,123
15209,2012-09-30 22:00,4,0,0,1,19.68,23.485,72,0.0000,15,76,91
15210,2012-09-30 23:00,4,0,0,1,19.68,23.485,72,6.0032,8,49,57

(15211, 12)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 0:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16
1,2011-01-01 1:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40
2,2011-01-01 2:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32
3,2011-01-01 3:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13
4,2011-01-01 4:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
15206,2012-09-30 19:00,4,0,0,3,20.50,24.240,72,8.9981,34,223,257
15207,2012-09-30 20:00,4,0,0,3,20.50,24.240,72,8.9981,31,163,194
15208,2012-09-30 21:00,4,0,0,1,20.50,24.240,68,0.0000,19,104,123
15209,2012-09-30 22:00,4,0,0,1,19.68,23.485,72,0.0000,15,76,91
15210,2012-09-30 23:00,4,0,0,1,19.68,23.485,72,6.0032,8,49,57

## (2) **[Down/Up Sampling]** 데이터의 빈도를 일(Day) 기준으로 변환하여 진행

In [5]:
# 결과확인(아래 변수명으로 사용 및 반드시 결과 출력할 것!)
display(df.head(), df.tail())
display(df.shape)
display(df_test.head(), df_test.tail())
display(df_test.shape)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 0:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16
1,2011-01-01 1:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40
2,2011-01-01 2:00,1,0,0,1,9.02,13.635,80,0.0,5,27,32
3,2011-01-01 3:00,1,0,0,1,9.84,14.395,75,0.0,3,10,13
4,2011-01-01 4:00,1,0,0,1,9.84,14.395,75,0.0,0,1,1

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
15206,2012-09-30 19:00,4,0,0,3,20.50,24.240,72,8.9981,34,223,257
15207,2012-09-30 20:00,4,0,0,3,20.50,24.240,72,8.9981,31,163,194
15208,2012-09-30 21:00,4,0,0,1,20.50,24.240,68,0.0000,19,104,123
15209,2012-09-30 22:00,4,0,0,1,19.68,23.485,72,0.0000,15,76,91
15210,2012-09-30 23:00,4,0,0,1,19.68,23.485,72,6.0032,8,49,57

(15211, 12)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 0:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16
1,2011-01-01 1:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40
2,2011-01-01 2:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32
3,2011-01-01 3:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13
4,2011-01-01 4:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
15206,2012-09-30 19:00,4,0,0,3,20.50,24.240,72,8.9981,34,223,257
15207,2012-09-30 20:00,4,0,0,3,20.50,24.240,72,8.9981,31,163,194
15208,2012-09-30 21:00,4,0,0,1,20.50,24.240,68,0.0000,19,104,123
15209,2012-09-30 22:00,4,0,0,1,19.68,23.485,72,0.0000,15,76,91
15210,2012-09-30 23:00,4,0,0,1,19.68,23.485,72,6.0032,8,49,57

## (3) **[Data Split]** 아래 지정된 내용으로 진행
> - Y: `count`
> - X: Y를 제외한 나머지
> - Train: 2011년 1월 ~ 2012년 6월 (18개월)
> - Validate: 2012년 7월 ~ 2012년 9월 (3개월)
> - Test: 2012년 10월 ~ 2012년 12월 (3개월)

`(1+2+3) 위 전처리 과정을 정리 후 함수로 작성 및 실행`

In [ ]:
# 결과확인(아래 변수명으로 사용 및 반드시 결과 출력할 것!)
display(X_train.shape, X_val.shape, X_test.shape, Y_train.shape, Y_val.shape, Y_test.shape)
display(Y_train, X_train.columns)
display(Y_val, X_val.columns)
display(Y_test, X_test.columns)

## (4) **[Train 시각화]**
> - 모든 독립변수들의 히스토그램(Histogram)
> - 모든 독립변수 별 종속변수의 분포 박스플랏(Boxplot): 필요에 따라 `시각화를 위한 독립변수의 구간화` 사용
> - 모든 독립변수와 종속변수의 상관관계 히드맵(Heatmap)

## (5) **[시간변수 추출]** 연/분기/월/주/일/요일/휴일/근무일/공휴일여부/명절여부 (`미국 워싱턴 기준`)

In [ ]:
# 결과확인(아래 변수명으로 사용 및 반드시 결과 출력할 것!)
display(X_train.shape, X_val.shape, X_test.shape, Y_train.shape, Y_val.shape, Y_test.shape)
display(Y_train, X_train.columns)
display(Y_val, X_val.columns)
display(Y_test, X_test.columns)

## (6) **[시간특징 추출]** 추세/계절성/이동평균/차분/지연값

In [ ]:
# 결과확인(아래 변수명으로 사용 및 반드시 결과 출력할 것!)
display(X_train.shape, X_val.shape, X_test.shape, Y_train.shape, Y_val.shape, Y_test.shape)
display(Y_train, X_train.columns)
display(Y_val, X_val.columns)
display(Y_test, X_test.columns)

## (7) **[파생변수 및 나머지 전처리]** `Y 예측에 도움이 될 것으로 예상되는 자유로운 변수생성 및 전처리`
> - 필요여부를 판단하여 주석으로 작성하되, 자유롭고 창의적인 파생변수를 생성 + 알고리즘 학습 전 나머지 필요한 전처리 진행

`(5+6+7) 위 전처리 과정을 정리 후 함수로 작성 및 실행`

In [ ]:
# 결과확인(아래 변수명으로 사용 및 반드시 결과 출력할 것!)
display(X_train.shape, X_val.shape, X_test.shape, Y_train.shape, Y_val.shape, Y_test.shape)
display(Y_train, X_train.columns)
display(Y_val, X_val.columns)
display(Y_test, X_test.columns)

## (8) **[Test 전처리]** 
> - Text 기간의 독립변수 값들은 미래가 도래해야만 생성되기 때문이 사용할 수가 없음
> - 자유롭고 창의적인 방법으로 Test 기간의 독립변수 값을 생성

In [ ]:
# 결과확인(아래 변수명으로 사용 및 반드시 결과 출력할 것!)
display(X_train.shape, X_val.shape, X_test.shape, Y_train.shape, Y_val.shape, Y_test.shape)
display(Y_train, X_train.columns)
display(Y_val, X_val.columns)
display(Y_test, X_test.columns)

# **Applying Algorithms:** Deep Learning

**(1)** 전처리 데이터에 `알고리즘` 사용하여 `학습(Train) 및 검증(Validate)` 예측 진행

- 사용 알고리즘은 최소 5종: (필수)`Stacking(base), MLP, CNN, RNN, LSTM` + (선택)`Others`
- 수업 외 성능을 향상될 수 있는 추가적인 알고리즘을 활용해도 되며, 각 알고리즘은 필요에 따라 하리퍼파라미터 튜닝 진행
- 딥러닝 알고리즘의 경우 학습을 위해서 `Reshape` 과정이 요구되는 경우 반영해야 하며, 성능 향상을 위한 `Walk Forward` 방식도 활용 가능

---

**(2)** `Train & Validate 예측값과 성능 검증지표`를 아래 표와 같이 제시하되, 검증지표는 `MSPE, MAPE, MedAPE 평균값을 기준으로 오름차순`

| **Datetime** | **Dataset** | **Y_true** | **Y_pred(Stacking)** | **Y_pred(MLP)** | **Y_pred(CNN)** | **Y_pred(RNN)** | **Y_pred(LSTM)** | **Y_pred(...)** |
|:---:|:---:|---|---|---|---|---|---|---|
| 2012년 1월 | Train |  |  |  |  |  |  |  |
| 2012년 2월 | Train |  |  |  |  |  |  |  |
| 2012년 3월 | Train |  |  |  |  |  |  |  |
| 2012년 4월 | Train |  |  |  |  |  |  |  |
| 2012년 5월 | Train |  |  |  |  |  |  |  |
| 2012년 6월 | Train |  |  |  |  |  |  |  |
| 2012년 7월 | Validate |  |  |  |  |  |  |  |
| 2012년 8월 | Validate |  |  |  |  |  |  |  |
| 2012년 9월 | Validate |  |  |  |  |  |  |  |

| **Dataset** | **Algorithm** | **RMSE** | **MSPE** | **MAE** | **MAPE** | **MedAE** | **MedAPE** | **Avg(MSPE+MAPE+MedAPE)** |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| Train | Stacking |  |  |  |  |  |  |  |
| Train | MLP |  |  |  |  |  |  |  |
| Train | CNN |  |  |  |  |  |  |  |
| Train | RNN |  |  |  |  |  |  |  |
| Train | LSTM |  |  |  |  |  |  |  |
| Train | … |  |  |  |  |  |  |  |

| **Dataset** | **Algorithm** | **RMSE** | **MSPE** | **MAE** | **MAPE** | **MedAE** | **MedAPE** | **Avg(MSPE+MAPE+MedAPE)** |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| Validate | Stacking |  |  |  |  |  |  |  |
| Validate | MLP |  |  |  |  |  |  |  |
| Validate | CNN |  |  |  |  |  |  |  |
| Validate | RNN |  |  |  |  |  |  |  |
| Validate | LSTM |  |  |  |  |  |  |  |
| Validate | … |  |  |  |  |  |  |  |

---

**(3)** `Train & Validate` 데이터의 예측 결과를 `시각화로 표현`하여 얼마나 정확한지 확인

- 5개의 모델링 Train 정답 Y와 예측 Y를 1개의 시각화로 표현하고, 동일하게 Validate 에 대해서도 1개의 시각화로 표현
- 비교 성능이 검증지표와 시각적으로 유사하게 나타나는지, 그리고 어떤 모델링이 적합한지 주석으로 의견 작성

## **(1)** 전처리 데이터에 `알고리즘` 사용하여 `학습(Train) 및 검증(Validate)` 예측 진행

- 사용 알고리즘은 최소 5종: (필수)`Stacking(base), MLP, CNN, RNN, LSTM` + (선택)`Others`
- 수업 외 성능을 향상될 수 있는 추가적인 알고리즘을 활용해도 되며, 각 알고리즘은 필요에 따라 하리퍼파라미터 튜닝 진행
- 딥러닝 알고리즘의 경우 학습을 위해서 `Reshape` 과정이 요구되는 경우 반영해야 하며, 성능 향상을 위한 `Walk Forward` 방식도 활용 가능

## **(2)** `Train & Validate 예측값과 성능 검증지표`를 아래 표와 같이 제시하되, 검증지표는 `MSPE, MAPE, MedAPE 평균값을 기준으로 오름차순`

| **Datetime** | **Dataset** | **Y_true** | **Y_pred(Stacking)** | **Y_pred(MLP)** | **Y_pred(CNN)** | **Y_pred(RNN)** | **Y_pred(LSTM)** | **Y_pred(...)** |
|:---:|:---:|---|---|---|---|---|---|---|
| 2012년 1월 | Train |  |  |  |  |  |  |  |
| 2012년 2월 | Train |  |  |  |  |  |  |  |
| 2012년 3월 | Train |  |  |  |  |  |  |  |
| 2012년 4월 | Train |  |  |  |  |  |  |  |
| 2012년 5월 | Train |  |  |  |  |  |  |  |
| 2012년 6월 | Train |  |  |  |  |  |  |  |
| 2012년 7월 | Validate |  |  |  |  |  |  |  |
| 2012년 8월 | Validate |  |  |  |  |  |  |  |
| 2012년 9월 | Validate |  |  |  |  |  |  |  |

| **Dataset** | **Algorithm** | **RMSE** | **MSPE** | **MAE** | **MAPE** | **MedAE** | **MedAPE** | **Avg(MSPE+MAPE+MedAPE)** |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| Train | Stacking |  |  |  |  |  |  |  |
| Train | MLP |  |  |  |  |  |  |  |
| Train | CNN |  |  |  |  |  |  |  |
| Train | RNN |  |  |  |  |  |  |  |
| Train | LSTM |  |  |  |  |  |  |  |
| Train | … |  |  |  |  |  |  |  |

| **Dataset** | **Algorithm** | **RMSE** | **MSPE** | **MAE** | **MAPE** | **MedAE** | **MedAPE** | **Avg(MSPE+MAPE+MedAPE)** |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| Validate | Stacking |  |  |  |  |  |  |  |
| Validate | MLP |  |  |  |  |  |  |  |
| Validate | CNN |  |  |  |  |  |  |  |
| Validate | RNN |  |  |  |  |  |  |  |
| Validate | LSTM |  |  |  |  |  |  |  |
| Validate | … |  |  |  |  |  |  |  |

## **(3)** `Train & Validate` 데이터의 예측 결과를 `시각화로 표현`하여 얼마나 정확한지 확인

- 10개의 모델링 Train 정답 Y와 예측 Y를 1개의 시각화로 표현하고, 동일하게 Validate 에 대해서도 1개의 시각화로 표현
- 비교 성능이 검증지표와 시각적으로 유사하게 나타나는지, 그리고 어떤 모델링이 적합한지 주석으로 의견 작성

# **Forecasting:** 실제 미래의 수요를 예측

**(1)** 모든 알고리즘의 미래 3개월(Test)을 예측해보고,

**(2)** `Test 예측값과 성능 검증지표`를 아래 표와 같이 제시하되, 검증지표는 `MSPE, MAPE, MedAPE 평균값을 기준으로 오름차순`

| **Datetime** | **Dataset** | **Y_true** | **Y_pred(Stacking)** | **Y_pred(MLP)** | **Y_pred(CNN)** | **Y_pred(RNN)** | **Y_pred(LSTM)** | **Y_pred(...)** |
|:---:|:---:|---|---|---|---|---|---|---|
| 2012년 10월 | Test |  |  |  |  |  |  |  |
| 2012년 11월 | Test |  |  |  |  |  |  |  |
| 2012년 12월 | Test |  |  |  |  |  |  |  |

| **Dataset** | **Algorithm** | **RMSE** | **MSPE** | **MAE** | **MAPE** | **MedAE** | **MedAPE** | **Avg(MSPE+MAPE+MedAPE)** |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| Test | Stacking |  |  |  |  |  |  |  |
| Test | MLP |  |  |  |  |  |  |  |
| Test | CNN |  |  |  |  |  |  |  |
| Test | RNN |  |  |  |  |  |  |  |
| Test | LSTM |  |  |  |  |  |  |  |
| Test | … |  |  |  |  |  |  |  |

**(3)** `Y정답과 Y예측을 시각화로 표현`하여 얼마나 현실성이 있는 예측이라고 생각하는지 주석으로 작성하고 미래의 수요를 기반으로 한 비즈니스 전략도 주석으로 작성

> (평가는 Base 제외한 알고리즘의 성능으로 판단)

In [ ]:
# 데이터 확인(아래 변수명으로 사용 및 반드시 결과 출력할 것!)
display(X_train.shape, X_val.shape, X_test.shape, Y_train.shape, Y_val.shape, Y_test.shape)
display(Y_train, X_train.columns)
display(Y_val, X_val.columns)
display(Y_test, X_test.columns)

## **(1)** 모든 알고리즘의 미래 3개월(Test)을 예측해보고,

## **(2)** `Test 예측값과 성능 검증지표`를 아래 표와 같이 제시하되, 검증지표는 `MSPE, MAPE, MedAPE 평균값을 기준으로 오름차순`

| **Datetime** | **Dataset** | **Y_true** | **Y_pred(Stacking)** | **Y_pred(MLP)** | **Y_pred(CNN)** | **Y_pred(RNN)** | **Y_pred(LSTM)** | **Y_pred(...)** |
|:---:|:---:|---|---|---|---|---|---|---|
| 2012년 10월 | Test |  |  |  |  |  |  |  |
| 2012년 11월 | Test |  |  |  |  |  |  |  |
| 2012년 12월 | Test |  |  |  |  |  |  |  |

| **Dataset** | **Algorithm** | **RMSE** | **MSPE** | **MAE** | **MAPE** | **MedAE** | **MedAPE** | **Avg(MSPE+MAPE+MedAPE)** |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| Test | Stacking |  |  |  |  |  |  |  |
| Test | MLP |  |  |  |  |  |  |  |
| Test | CNN |  |  |  |  |  |  |  |
| Test | RNN |  |  |  |  |  |  |  |
| Test | LSTM |  |  |  |  |  |  |  |
| Test | … |  |  |  |  |  |  |  |

## **(3)** `Y정답과 Y예측을 시각화로 표현`하여 얼마나 현실성이 있는 예측이라고 생각하는지 주석으로 작성하고 미래의 수요를 기반으로 한 비즈니스 전략도 주석으로 작성
> (평가는 Base 제외한 알고리즘의 성능으로 판단)

In [7]:
### 시작 및 본인정보 반영
# 반드시 이 cell을 실행하시오
# 실행하지 않을 시 직접 하지 않은 것으로 간주
# 마지막 줄 출력으로 파일명을 설정하고 제출 필수
import platform, psutil, os, datetime
print(platform.processor())
print(str(round(psutil.virtual_memory().total / (1024.0 **3)))+"(GB)")
print(platform.system())
print(platform.version())
print(os.getcwd())
print(datetime.datetime.fromtimestamp(os.path.getctime(os.getcwd())))
print(datetime.datetime.fromtimestamp(os.path.getmtime(os.getcwd())))
print(datetime.datetime.fromtimestamp(os.path.getatime(os.getcwd())))
print(datetime.datetime.now())
title = 'DL_TimeSeries_Forecasting'    # 고정값
name = '김경원'    # 본인 이름을 작성
studentid = '20211011'    # 본인 학번을 작성
# 아래 강좌 명 중 본인이 수강하는 강과명 작성
# 비즈니스데이터사이언스이해, 디지털비즈니스애널리틱스, 비즈니스수요예측, 인공지능기반의사결정, 빅데이터 등
# 비즈니스혁신을위한데이터사이언스응용, 인공지능활용디지털경제플랫폼연구 등
course = '비즈니스수요예측'    
print('다음 출력을 파일명으로 설정하고 제출하시오:', name + '_' + studentid + '_' + course + '_' + title)

Intel64 Family 6 Model 186 Stepping 2, GenuineIntel
32(GB)
Windows
10.0.26200
C:\DataScience\Lecture\[DataScience]
2024-12-12 00:34:16.155373
2025-11-13 15:10:31.012904
2025-11-13 15:10:31.012904
2025-11-13 15:10:32.694185
다음 출력을 파일명으로 설정하고 제출하시오: 김경원_20211011_비즈니스수요예측_DL_TimeSeries_Forecasting